name: design-tokens

on:
  push:
    branches: [main]
    paths:
      - "design-tokens/**"
  pull_request:
    paths:
      - "design-tokens/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-tokens
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm run build
